### ISSUE TITLE
Validation styles with pre-pended icon

### ISSUE THREAD

**Issue by wojtj** [creativetimofficial/ct-argon-dashboard-pro#1]
When using bootstrap validation, when the :valid and :invalid styles are applied to a control, the outline of the form control changes colour, as expected.

However, if there is a prepended icon, the icon border colour does not change, and the right-hand border loses the rounding.

`    <div class="form-group">
        <div class="input-group input-group-merge">
            <div class="input-group-prepend">
                <span class="input-group-text">
                    <i class="fal fa-key"></i>
                </span>
            </div>
            <input asp-for="Password" type="password" placeholder="Password" class="form-control">
        </div>
    </div>`

Before validation:
![before](https://user-images.githubusercontent.com/8101578/50730481-5a1a4500-11b3-11e9-835e-32d60e720769.PNG)

After validation:
![after](https://user-images.githubusercontent.com/8101578/50730485-643c4380-11b3-11e9-9e89-a70724fb9195.PNG)

**Comment by extrabright** [comment]
Thanks for the heads up! I know about this issue. Just didn't cover this scenario too. I will try to add this validation feature for input groups too in the next update.
