### ISSUE TITLE
New spinner class in bootstrap 4.3 not included in argon.css

### ISSUE THREAD

**Issue by AnotherIdea** [creativetimofficial/ct-argon-dashboard-pro#10]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Spinner class should be included in css
https://getbootstrap.com/docs/4.3/components/spinners/

# Current Behavior

Spinner class does not exist and are not working

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. download argon-pro v1.1.0
2. use it in an html page with 
```
<div class="spinner-border" role="status">
  <span class="sr-only">Loading...</span>
</div>
```
3. Spinner doesn't appear

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

Thank you for pointing this to us. We will make the spinners work in our next update.

Until then please add these lines of code to have the spinner functionality:
 In the css:
```
@keyframes rotate {
  to {transform: rotate(360deg);}
}

.spinner-border {
    display: inline-block;
    width: 2rem;
    height: 2rem;
    vertical-align: text-bottom;
    border: .25em solid currentColor;
    border-right-color: transparent;
    border-radius: 50%;
    -webkit-animation: spinner-border .75s linear infinite;
    animation: rotate 1s linear infinite;
}
```

Then use the spinner with:
```
<div class="spinner-border" role="status">
  <span class="sr-only">Loading...</span>
</div>
```

I hope it helps.

All the best,
Rares

**Comment by AnotherIdea** [comment]
Thank you
