### ISSUE TITLE
Datatable Excel, PDF Export

### ISSUE THREAD

**Issue by Parth-Kadakia** [creativetimofficial/ct-argon-dashboard-pro#12]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes ] I am running the latest version
- [ Yes] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

For the datatable, I have added in dom : Bfrtip and buttons as copy, excel, pdf, print.

It should show all the buttons

# Current Behavior

It only displays COPY and Print

# Failure Information (for bugs)

**Comment by Parth-Kadakia** [comment]
I was able to get it working but...

1. If you use the Datatable javascript provided in the asset folder, it does not work. If I download the javascript from the Datatables website and call it, it works. 

I am thinking there is an issue with the project javascript.

**Comment by rarestoma** [comment]
Hello,

We will take a closer look to see how it should work in the next update.

Now it is working for you?

All the best,
Rares

**Comment by Parth-Kadakia** [comment]
It is currently working for me. Thanks.
