### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Parth-Kadakia** [creativetimofficial/ct-argon-dashboard-pro#13]
This is not an issue, more of a question.

I want to utilize the FullCalendar Plugin that is available. How do I make sure it does not pull up the default calendar that is part of Argon.JS file?

Thanks
Parth

**Comment by rarestoma** [comment]
Hi @Parth-Kadakia,

Thank you for working with our products.

If you want to add one more calendar you have to set a different ID on it.

All the best,
Rares
