### ISSUE TITLE
active on nav-link

### ISSUE THREAD

**Issue by ivenspontes** [creativetimofficial/ct-argon-dashboard-pro#15]
How automatic add active on nav-link?

**Comment by rarestoma** [comment]
Hi @ivenspontes,

Thank you for working with our products. Please add this function to the javascript code:

$(function(){
    var current = location.pathname;
    $('nav ul li a').each(function(){
        var this_link = $(this);
        this_link.addClass('active');
    })
});

I hope it helps.

All the best, 
Rares
