### ISSUE TITLE
Multiple select with search is not working.

### ISSUE THREAD

**Issue by cyrilxx** [creativetimofficial/ct-argon-dashboard-pro#18]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [X ] I checked the documentation and found no answer
- [X ] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
Multiple select should be working with data-live-search

# Current Behavior
What is the current behavior?
Multiple select with search is not working.

**Comment by rarestoma** [comment]
Hi @cyrilxx,

Thank you for working with our products.

Can you please show me a jsfiddle with your code so I can see clearly what happened?

Thank you,
Rares
