### ISSUE TITLE
Request : Tabs

### ISSUE THREAD

**Issue by Parth-Kadakia** [creativetimofficial/ct-argon-dashboard-pro#24]
This is more like a request or support question for whether its possible or not. 

For Vue-Argon project you have tabs supported

https://demos.creative-tim.com/vue-argon-design-system/documentation/components/tabs.html

Is it possible to do the same in Argon Dashboard Pro?

Parth

**Comment by rarestoma** [comment]
Hi @Parth-Kadakia,

The navs are designed for the Argon Dashboard PRO. We have to add it also to our documentation.

Please test this code:

`
<div class="nav-wrapper">
<ul role="tablist" class="nav nav-pills nav-fill">
<li class="nav-item">
<a data-toggle="tab" role="tab" href="#UI/UX Design" class="nav-link active" aria-selected="true"><div>UI/UX Design</div>
</a>
</li>
<li class="nav-item">
<a data-toggle="tab" role="tab" href="#Programming" class="nav-link">
<div>Programming</div>
</a>
</li>
<li class="nav-item">
<a data-toggle="tab" role="tab" href="#Graphic" class="nav-link">
<div>Graphic</div>
</a>
</li>
</ul>
</div>
`

Please let me know if it works.

All the best,
Rares

**Comment by Parth-Kadakia** [comment]
That works. 

Thank you
Parth
