### ISSUE TITLE
Chartjs 3.0 : Argon.js config file need changes to avoid breaking changes

### ISSUE THREAD

**Issue by navidemad** [creativetimofficial/ct-argon-dashboard-pro#29]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

No warning related to deprecated Chartjs config.

# Current Behavior

Actually, the theme is working very well with Chartjs 2.9.3.
I upgraded to the version 3.0, and there is some breaking changes that you can find :
https://www.chartjs.org/docs/next/getting-started/v3-migration.html

Is it possible for you to make the appropriate changes into the theme argon ?

Thanks

**Comment by rarestoma** [comment]
Hi @navidemad,

Thank you for working with our products.

I added it to the list for the next update. Until then, please use v2.9.3 so all the charts will work properly.

Thank you,
Rares
