### ISSUE TITLE
chart's negative bar issue

### ISSUE THREAD

**Issue by VictorSlate** [creativetimofficial/ct-argon-dashboard-pro#32]
It's like a graphic issue. Please take a look:
![1588165268535](https://user-images.githubusercontent.com/4855930/80599282-4a380b80-8a5d-11ea-94e4-21836d217e2c.jpg)
![1588165232376](https://user-images.githubusercontent.com/4855930/80599290-4c9a6580-8a5d-11ea-96bf-a224f589f961.jpg)

**Comment by rarestoma** [comment]
Hi @VictorSlate,

Thank you for working with our products.

This error is from Chart.extension.js that is making the bars rounded. Please remove the import for this file:   `<script src="../../assets/vendor/chart.js/dist/Chart.extension.js"></script>`

Please let me know if it works.

Thank you,
Rares
