### ISSUE TITLE
ncaught TypeError: $(...).autocomplete is not a function     at Object.success (create:708)     at c (jquery.min.js:2)     at Object.fireWith [as resolveWith] (jquery.min.js:2)     at l (jquery.min.js:2)     at XMLHttpRequest.<anonymous> (jquery.min.js:2) create:702 Uncaught TypeError: $(...).autocomplete is not a function     at Object.success (create:702)     at c (jquery.min.js:2)     at Object.fireWith [as resolveWith] (jquery.min.js:2)     at l (jquery.min.js:2)     at XMLHttpRequest.<anonymous> (jquery.min.js:2)

### ISSUE THREAD

**Issue by yogesh80** [creativetimofficial/ct-argon-dashboard-pro#38]

**Comment by mratre217** [comment]
!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Program in html</title>
    <style type="text/css">
        .container{overflow: hidden;}
        .tab{float: left;}
        .tab-2 {margin-left: 50px;}
        .tab-2 input{display: block;margin-bottom: 20px;}

    </style>
</head>
<body>
    <div id="container">
        <div class="tab tab-1">
            <table id="table" >

           <tr>
               <th> first name</th>
               <th>last name</th>
              <th>age</th>
           </tr>
        </table>


    </div>
    <div class="tab tab-2">
        first name:<input type="text" name="fname" id="fname">
        last name:<input type="text" name="lname" id="lname">
        age:<input type="text" name="age" id="age">
        <button onclick="addRow();">Add</button>
        <button>Edit</button>
        <button>Remove</button>
    </div>
       </div>
    <script>


        function addRow()
        {
         var table = document.getElementById("table")[0];

         var newRow = table.insertRow(0);

         var cell1 = NewRow.insertCell(0);
         var cell2 = NewRow.insertCell(1);
         var cell3 = NewRow.insertCell(2);

         var fname = document.getElementById("fname").value;
         var lname = document.getElementById("lname").value;
         var age = document.getElementById("age").value;

         cell1.innerHTML = "fname";
         cell2.innerHTML = "lname";
         cell3.innerHTML = "age";


        }

    </script>
</body>
</html>

**Comment by mratre217** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'insertRow')
    at addRow (index.html:46)
    at HTMLButtonElement.onclick (index.html:34)
why is seeing like this

**Comment by rarestoma** [comment]
Hi @mratre217,

Thank you for working with our products.

Can you please give me more details about your issue?

Thank you,
Rares
