### ISSUE TITLE
Table width does not change

### ISSUE THREAD

**Issue by rodrigoalexandrino** [creativetimofficial/ct-argon-dashboard-pro#4]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X ] I am running the latest version
- [ X] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When using a table with many columns, it should adjust itself according to the size of the screen

# Current Behavior

When using a table with many columns, it should adjust itself according to the size of the screen

# Failure Information (for bugs)

I believe the error is in the .table class, its settings are in the 'css / argon.css' file, when it removes this class, the table fits, but loses all its style

## Steps to Reproduce

Create some table with many columns

**Comment by rarestoma** [comment]
Hello,

Sorry for the late response.

Can you please show us a photo with this issue? We tried to replicate it but seems it works fine.

All the best,
Rares
