### ISSUE TITLE
Question about package contents

### ISSUE THREAD

**Issue by chris-energylinx** [creativetimofficial/ct-argon-dashboard-pro#5]
Hi all,

very happy with the quality of thje product as such, thank you, however I'm struggling to find a couple of things:

1) It says that the "Pro" version should have 25 example pages. However in the downloaded HTML assets I only find 6. I couldn't find these in online demos or documentation either.  What am I missing, where should I look?

2) Is there a way to have the entire documentation as a package in the HTML download so I canwork with it locally? In the download there are no plugins and many components missing. So if I want to demo all the available components and plugins in my brand I need to build all of that from scratch locally which is a considerable amount of work ... which is exactly why I purchased the design system/dashboard in the first place :)

In addition, when I work on airplanes and trains I may not always have access to the online docs.

Thanks and keep up the good work!

Chris

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products and sorry for our late response.

All the links from the sidebar(example: Dashboard, Widgets, Extended Forms, Regular Forms, Buttons, etc) represents Example Pages, so if you will count these links you will see that are 25 Example Pages + 1 Index page.

Unfortunately, you can not have the files downloaded... We will take in consideration this thing in the future.

All the best,
Rares
