### ISSUE TITLE
[Feature Request] Chat UI

### ISSUE THREAD

**Issue by The-MG** [creativetimofficial/ct-argon-dashboard-pro#54]
### What is your enhancement?
Argon 2 is an amazing product, however, I would've loved to see a chat UI.

Regards,
The MG

**Comment by rarestoma** [comment]
Hi @The-MG,

Thank you for working with our products.

I just added your request to be added in our next update.

Best regards,
Rares

**Comment by willians1002** [comment]
Hi,

I believe this issue can be closed as a chat UI is included was included on the new Argon Dashboard 2 PRO.
You can see it on the [live preview website](https://demos.creative-tim.com/argon-dashboard-pro/pages/pages/chat.html).

Best regards,
Willian Oliveira

**Comment by The-MG** [comment]
That is nice to know. Thanks for including it!

**Comment by The-MG** [comment]
> Hi,
> 
> I believe this issue can be closed as a chat UI is included on the new Argon Dashboard 2 PRO. You can see it on the [live preview website](https://demos.creative-tim.com/argon-dashboard-pro/pages/pages/chat.html).
> 
> Best regards, Willian Oliveira

It seems that it no longer exists, is there a reason why?

**Comment by groovemen** [comment]
Hello @The-MG,

Thank you for using our products, we will add the page back into the next product update. 
Sorry for this inconvenience. 

All the best,
Stefan

**Comment by The-MG** [comment]
Thank you so much.

**Comment by groovemen** [comment]
Hello @The-MG,

We have updated the product, you can check out here the [Chat Page](https://demos.creative-tim.com/argon-dashboard-pro/pages/pages/chat.html) 
Cheers, 
Stefan

**Comment by The-MG** [comment]
> Hello @The-MG,
> 
> We have updated the product, you can check out here the [Chat Page](https://demos.creative-tim.com/argon-dashboard-pro/pages/pages/chat.html) Cheers, Stefan

Thank you so much!
