### ISSUE TITLE
"Checkbox + Toggles" table example, checkboxes issue

### ISSUE THREAD

**Issue by ezehnder** [creativetimofficial/ct-argon-dashboard-pro#6]
There seems to be an issue on this page:
https://demos.creative-tim.com/argon-dashboard-pro/pages/tables/tables.html

Under "Checkbox + Toggles" table, clicking on any checkbox on the left side only toggles the header checkbox.

Expected behavior: Toggling header checkbox should toggle all rows' checkboxes. Clicking each row checkbox should only toggle the row checkbox.

Tested on Windows 10, both Firefox and Chrome.

Thanks.

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

You have to add different id's on each checkbox so you can check each one.

To check all you have to add some javascript code like the following:

function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
}

And the add onclick attribute on the input like the following:
<input type="checkbox" **onclick="toggle(this)**;" />Check all?<br />

Hope it helps.

All the best,
Rares

**Comment by dreamhigh915** [comment]
Hi.
The above comment might not work well.
Kindly add this to your check box class.  (checklist-entry)
Like this.

<input class="custom-control-input checklist-entry" id="customCheck1" type="checkbox">

Will work well surely.

Thank you.
