### ISSUE TITLE
[Bug] Task "gulp build" never defined

### ISSUE THREAD

**Issue by filippotoso** [creativetimofficial/ct-argon-dashboard-pro#61]
### Version
2.0.1
### Reproduction link
https://www.example.com/
### Operating System
Windows 10
### Device
Laptop
### Browser & Version
Chrome 99
### Steps to reproduce
Download Argon Dashboard Pro 2.0.1
Run: npm install
Run: gulp build
### What is expected?
I expect to obtain a dist folder with the compiled assets.
### What is actually happening?
I get the "Task never defined: build" error message

[08:39:00] Using gulpfile D:\Purchase\creative-tim\argon-dashboard-pro-html-v2.0.1\argon-dashboard-pro-html-v2.0.1\gulpfile.js
[08:39:00] Task never defined: build
[08:39:00] To list available tasks, try running: gulp --tasks

---

**Comment by groovemen** [comment]
Hello @filippotoso, 

Thank you for using our products, we have answered on Zendesk to your issue. 

Best, 
Stefan
