### ISSUE TITLE
Select2 multiple tag bug

### ISSUE THREAD

**Issue by assisjeferson** [creativetimofficial/ct-argon-dashboard-pro#7]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

When I try use multiple select2, the input field dissapear

# Current Behavior

<img width="457" alt="Screen Shot 2019-05-14 at 17 06 46" src="https://user-images.githubusercontent.com/331113/57728611-b82bcd00-766a-11e9-91ba-3ddf924f4d2b.png">

Expected:

<img width="471" alt="Screen Shot 2019-05-14 at 17 08 04" src="https://user-images.githubusercontent.com/331113/57728676-dbef1300-766a-11e9-85b7-584739fb902d.png">

# Failure Information (for bugs)

Select with `multiple="multiple"` 

``<select name="college_id[]" multiple="multiple" class="form-control college-ajax-finding"></select>``

If remove the class  `.select2-container .select2-search--inline{ display: none;}`, the plugin work fine

**Comment by rarestoma** [comment]
Hello,

Thank you for working with our products.

Did it work if you remove .select2-container .select2-search--inline{display:none;} ? Please let me know if you need help with anything else?

All the best,
Rares

**Comment by assisjeferson** [comment]
Hello @rarestoma,

Yeah, removing that line the plugin work fine.
