### ISSUE TITLE
Dropdown menu within table shows a scrollbar when opened

### ISSUE THREAD

**Issue by ezehnder** [creativetimofficial/ct-argon-dashboard-pro#8]
When using the dropdown menu within a table cell:

```
<td class="text-right">
  <div class="dropdown">
    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-ellipsis-v"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
</td>
```

like shown on this page: 
https://demos.creative-tim.com/argon-dashboard-pro/pages/tables/tables.html

an undesired scrollbar shows up if the table has only a few rows (for example 1 row) and action links take up more height than the table's height.

Here is a screenshot to illustrate:

![image](https://user-images.githubusercontent.com/33011219/58763388-66bb8300-8530-11e9-8cb5-b95b143db8d3.png)

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

To fix that, please add 'overflow-visible' class on the div just before the table.

It will look like:

<div class="table-responsive overflow-visible">
              <table class="table align-items-center table-flush">
                     ...
              </table>
</div>

All the best,
Rares

**Comment by assisjeferson** [comment]
@rarestoma it's dont work when you use in mobile

Add `data-boundary="window"` in the dropdown

```
<td class="text-right">
  <div class="dropdown">
    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-boundary="window">
      <i class="fas fa-ellipsis-v"></i>
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
</td>
```

But you use `.table-responsive` in iOS the button dont work because has a bug with css (webkit-overflow-scrolling)

**Comment by rarestoma** [comment]
Hi,

Sorry for our last response :(

I tested it with just data-boundary="window" and it works fine.

Did you try this way?

All the best,
Rares

**Comment by Austinbreathesair** [comment]
I'm currently experiencing issues with the drop-down components. I use the ones from the docs but on my side when selecting the button it doesn't present the drop-down fields.

```<div class="col-md-6">
      <div class="btn-group">
        <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">Allocate Performer Group</button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Separated link</a>
        </div>
      </div>
    </div>
```

**Comment by jaisankargopal** [comment]
I'm facing the similar problem. Drop down list covering by  the    class="ct-chart"

[list.txt](https://github.com/creativetimofficial/ct-argon-dashboard-pro/files/4039887/list.txt)
  
[drpdwn.docx](https://github.com/creativetimofficial/ct-argon-dashboard-pro/files/4039923/drpdwn.docx)

**Comment by jaisankargopal** [comment]
I'm facing the similar problem. Drop down list covering by the class="ct-chart"



 
![image](https://user-images.githubusercontent.com/8012061/72126036-ad0f7500-3390-11ea-9b0c-5744b9bdb961.png)

**Comment by rarestoma** [comment]
Hi @jaisankargopal,

Thank you for working with our products. I see that you are using our Material Dashboard. Please open a issue at the Material Dashboard official repo: 

Free Version: https://github.com/creativetimofficial/material-dashboard/issues
PRO Version: https://github.com/creativetimofficial/ct-material-dashboard-pro/issues

I hope it helps.

All the best,
Rares

**Comment by jaisankargopal** [comment]
Thanks.
