### ISSUE TITLE
Django Templates / Scrollbar js does not work

### ISSUE THREAD

**Issue by rmznovali** [creativetimofficial/ct-argon-dashboard-pro#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [yes ] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [yes ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

I have been trying to implement Argon Dashboard for my website admin. I just copied the code from the examples files, but the scroll does not look like yours and the open close sidebar does not work.

I use Django. I have created an base html where I put all the js and css. 

I extend to this file but scrollbar does not work. 

you can see the problems at dev.rezervo.io 
Thanks.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by rarestoma** [comment]
Hi,

Thank you for working with our products.

We visited https://dev.rezervo.io/ and it seems everything is working. Can you please send us a short video to see what exactly happens when you test it?

All the best,
Rares
